// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmdr59vQ9YPHjT92yNh7rNFUbG4NWRmE',
    appId: '1:522465768812:web:61c94848f0f0026bfcaf49',
    messagingSenderId: '522465768812',
    projectId: 'sekum-c8805',
    authDomain: 'sekum-c8805.firebaseapp.com',
    storageBucket: 'sekum-c8805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKPyZJZxIEfJ-XOLtOnwV9utGF1PDFNY',
    appId: '1:522465768812:android:70a864f996f2fdd7fcaf49',
    messagingSenderId: '522465768812',
    projectId: 'sekum-c8805',
    storageBucket: 'sekum-c8805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmlTCwAbBVCYEAFYAIVcroeempZaNplM',
    appId: '1:522465768812:ios:a7620af2df393faafcaf49',
    messagingSenderId: '522465768812',
    projectId: 'sekum-c8805',
    storageBucket: 'sekum-c8805.appspot.com',
    iosBundleId: 'com.example.sekum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmlTCwAbBVCYEAFYAIVcroeempZaNplM',
    appId: '1:522465768812:ios:a7620af2df393faafcaf49',
    messagingSenderId: '522465768812',
    projectId: 'sekum-c8805',
    storageBucket: 'sekum-c8805.appspot.com',
    iosBundleId: 'com.example.sekum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmdr59vQ9YPHjT92yNh7rNFUbG4NWRmE',
    appId: '1:522465768812:web:a10950257a2b01b8fcaf49',
    messagingSenderId: '522465768812',
    projectId: 'sekum-c8805',
    authDomain: 'sekum-c8805.firebaseapp.com',
    storageBucket: 'sekum-c8805.appspot.com',
  );
}
